loadtest: 
  name: social-network-loadtest
  locust_locustfile_configmap: social-network-locustfile
  locust_host: "http://nginx-thrift.social-network:8080"

nodeSelector:
  "kubernetes.io/hostname": k8s-master

service:
  type: ClusterIP

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    value: "true"
  - effect: NoSchedule
    key: unschedulable
    value: "true"

worker: 
  replicas: 2
