image:
  repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
  tag: v0.10.3
  pullPolicy: IfNotPresent

loadtest: 
  name: online-boutique-loadtest
  locust_locustfile_configmap: online-boutique-locustfile
  locust_host: "http://frontend.online-boutique"

nodeSelector:
  "kubernetes.io/hostname": k8s-master

service:
  type: ClusterIP

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    value: "true"
  - effect: NoSchedule
    key: unschedulable
    value: "true"

worker: 
  command: ["locust", "--worker"]
  replicas: 2

master:
  command: ["locust", "--host=http://frontend.online-boutique"]
