apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 382452224.0
          requests:
            cpu: 0.018
            memory: 382452224.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.066
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.01
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.12
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.01
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.251
            memory: 104857600.0

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jaeger
#   namespace: online-boutique
# spec:
#   template:
#     spec:
#       containers:
#       - name: jaeger
#         resources:
#           limits:
#             cpu: null
#             memory: 919708416.0
#           requests:
#             cpu: 0.011
#             memory: 619708416.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: otel-gateway
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.014
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.01
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.076
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.126
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.011
            memory: 104857600.0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: online-boutique
spec:
  template:
    spec:
      containers:
      - name: server
        resources:
          limits:
            cpu: null
            memory: 104857600.0
          requests:
            cpu: 0.01
            memory: 104857600.0

---
