apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

helmGlobals:
 chartHome: ../charts

helmCharts:
  - name: online-boutique
    releaseName: online-boutique
    namespace: online-boutique
    valuesFile: values.yaml

resources:
  - ./namespace.yaml
  # - ./jaeger.yaml

patches:
  - path: ./patches/opentelemetry.yaml
  - path: ./patches/images.yaml
  # - path: ./patches/deployment-node.yaml
  # - path: ./patches/no-resources.yaml
  - path: ./patches/resources.yaml
  - patch: |
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: loadgenerator
        namespace: online-boutique
  #   - patch: |
  #       $patch: delete
  #       apiVersion: v1
  #       kind: Service
  #       metadata:
  #         name: jaeger
  #   - patch: |
  #       $patch: delete
  #       apiVersion: apps/v1
  #       kind: Deployment
  #       metadata:
  #         name: jaeger-hotel-reservation-hotelres
  #   - path: ./patches/deployment-node.yaml
  #   - path: ./patches/resources.yaml
  #   # - path: ./patches/no-resources.yaml
