apiVersion: batch/v1
kind: Job
metadata:
  name: init-social-network
  namespace: social-network
spec:
  template:
    spec:
      restartPolicy: Never

      initContainers:
      - name: wait-for-nginx
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          until nc -z nginx-thrift 8080; do
            echo "Waiting for nginx-thrift:8080..."
            sleep 2
          done
          echo "nginx-thrift is ready."

      containers:
      - name: init
        image: dclandau/initsocialgraph:4181ebd
        env:
        - name: PYTHONUNBUFFERED
          value: "1" 
        args:
        - --ip
        - nginx-thrift
        - --port
        - "8080"
